# Generated by Django 5.2.4 on 2026-01-18 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactmessage",
            old_name="messages",
            new_name="message",
        ),
    ]
